export type Locale = "en" | "id" | "th" | "vi" | "ms" | "fr" | "zh" | "ja" | "ko" | "ar" | "hi" | "es" | "de" | "pt" | "ru" | "tl";
export type TranslationKey = keyof typeof translations;

export const translations = {
  // ── App branding ──────────────────────────────────────────────────────────────
  "app.tagline":        { en: "Anonymous Dating",              id: "Kencan Anonim",                         th: "หาคู่แบบไม่เปิดเผยตัว",          vi: "Hẹn hò ẩn danh",                ms: "Temu kenalan tanpa nama",           fr: "Rencontres anonymes",            zh: "匿名交友",                       ja: "匿名マッチング",                  ko: "익명 데이팅",                    ar: "مواعدة مجهولة",                  hi: "गुमनाम डेटिंग",                  es: "Citas anónimas",                de: "Anonymes Dating",               pt: "Namoro anônimo",                ru: "Анонимные знакомства",          tl: "Anonymous na Pakikipagsosyo" },
  "app.name":           { en: "Mr Butlas",                     id: "Mr Butlas",                             th: "Mr Butlas",                        vi: "Mr Butlas",                      ms: "Mr Butlas",                         fr: "Mr Butlas",                      zh: "Mr Butlas",                     ja: "Mr Butlas",                      ko: "Mr Butlas",                      ar: "Mr Butlas",                      hi: "Mr Butlas",                      es: "Mr Butlas",                     de: "Mr Butlas",                     pt: "Mr Butlas",                     ru: "Mr Butlas",                     tl: "Mr Butlas" },

  // ── Navigation ────────────────────────────────────────────────────────────────
  "nav.ghostMode":      { en: "Ghost Mode",                    id: "Ghost Mode",                            th: "Ghost Mode",                       vi: "Ghost Mode",                     ms: "Ghost Mode",                        fr: "Ghost Mode",                     zh: "幽灵模式",                       ja: "ゴーストモード",                  ko: "고스트 모드",                    ar: "وضع الشبح",                      hi: "घोस्ट मोड",                      es: "Modo Fantasma",                 de: "Ghost-Modus",                   pt: "Modo Fantasma",                 ru: "Режим призрака",                tl: "Ghost Mode" },
  "nav.membersOnly":    { en: "Members only · Join to explore", id: "Khusus anggota · Daftar untuk menjelajah", th: "สำหรับสมาชิกเท่านั้น · เข้าร่วมเพื่อสำรวจ", vi: "Chỉ dành cho thành viên · Tham gia để khám phá", ms: "Ahli sahaja · Sertai untuk meneroka", fr: "Membres uniquement · Rejoindre pour explorer", zh: "仅限会员 · 加入探索",            ja: "会員限定 · 参加して探索",         ko: "회원 전용 · 가입하여 탐색",       ar: "للأعضاء فقط · انضم للاستكشاف",   hi: "केवल सदस्य · जुड़ें और खोजें",   es: "Solo miembros · Únete a explorar", de: "Nur Mitglieder · Beitreten und entdecken", pt: "Somente membros · Entre para explorar", ru: "Только для членов · Присоединитесь", tl: "Miyembro lamang · Sumali upang tuklasin" },
  "nav.signIn":         { en: "Sign in",                       id: "Masuk",                                 th: "เข้าสู่ระบบ",                      vi: "Đăng nhập",                      ms: "Log masuk",                         fr: "Se connecter",                   zh: "登录",                           ja: "サインイン",                      ko: "로그인",                          ar: "تسجيل الدخول",                   hi: "साइन इन करें",                   es: "Iniciar sesión",                de: "Anmelden",                      pt: "Entrar",                        ru: "Войти",                         tl: "Mag-sign in" },
  "nav.filters":        { en: "Filters",                       id: "Filter",                                th: "ตัวกรอง",                          vi: "Bộ lọc",                         ms: "Penapis",                           fr: "Filtres",                        zh: "筛选",                           ja: "フィルター",                      ko: "필터",                            ar: "مرشحات",                         hi: "फ़िल्टर",                         es: "Filtros",                       de: "Filter",                        pt: "Filtros",                       ru: "Фильтры",                       tl: "Mga Filter" },

  // ── Feed ──────────────────────────────────────────────────────────────────────
  "feed.activeNear":    { en: "Guests active near you",        id: "Anggota Ghost aktif di dekat Anda",     th: "สมาชิก Ghost ที่ใช้งานอยู่ใกล้คุณ", vi: "Thành viên Ghost đang hoạt động gần bạn", ms: "Ahli Ghost aktif berhampiran anda", fr: "Membres Ghost actifs près de vous", zh: "附近活跃的会员",                  ja: "あなたの近くのアクティブな会員",   ko: "근처 활성 게스트",                ar: "الضيوف النشطون بالقرب منك",      hi: "आपके पास सक्रिय मेहमान",         es: "Huéspedes activos cerca de ti", de: "Aktive Gäste in der Nähe",      pt: "Hóspedes ativos perto de você", ru: "Активные гости рядом с вами",   tl: "Mga aktibong bisita malapit sa iyo" },
  "feed.profiles":      { en: "Profiles",                      id: "Profil",                                th: "โปรไฟล์",                          vi: "Hồ sơ",                          ms: "Profil",                            fr: "Profils",                        zh: "档案",                           ja: "プロフィール",                    ko: "프로필",                          ar: "الملفات الشخصية",                hi: "प्रोफाइल",                        es: "Perfiles",                      de: "Profile",                       pt: "Perfis",                        ru: "Профили",                       tl: "Mga Profile" },
  "feed.onlineNow":     { en: "Online now",                    id: "Online sekarang",                       th: "ออนไลน์อยู่",                      vi: "Đang trực tuyến",                ms: "Dalam talian sekarang",             fr: "En ligne maintenant",            zh: "现在在线",                       ja: "オンライン中",                    ko: "지금 온라인",                     ar: "متصل الآن",                      hi: "अभी ऑनलाइन",                     es: "En línea ahora",                de: "Jetzt online",                  pt: "Online agora",                  ru: "Сейчас онлайн",                 tl: "Online ngayon" },
  "feed.countries":     { en: "Countries",                     id: "Negara",                                th: "ประเทศ",                           vi: "Quốc gia",                       ms: "Negara",                            fr: "Pays",                           zh: "国家",                           ja: "国",                             ko: "국가",                            ar: "الدول",                          hi: "देश",                             es: "Países",                        de: "Länder",                        pt: "Países",                        ru: "Страны",                        tl: "Mga Bansa" },
  "feed.activeToday":   { en: "Active today",                  id: "Aktif hari ini",                        th: "ใช้งานวันนี้",                     vi: "Hoạt động hôm nay",              ms: "Aktif hari ini",                    fr: "Actif aujourd'hui",              zh: "今天活跃",                       ja: "本日アクティブ",                  ko: "오늘 활성",                       ar: "نشط اليوم",                      hi: "आज सक्रिय",                      es: "Activo hoy",                    de: "Heute aktiv",                   pt: "Ativo hoje",                    ru: "Активен сегодня",               tl: "Aktibo ngayon" },
  "feed.browsing":      { en: "Browsing",                      id: "Menjelajah",                            th: "กำลังดู",                          vi: "Đang xem",                       ms: "Melayari",                          fr: "Parcourir",                      zh: "浏览中",                         ja: "閲覧中",                          ko: "탐색 중",                         ar: "يتصفح",                          hi: "ब्राउज़ कर रहे हैं",               es: "Explorando",                    de: "Durchsuchen",                   pt: "Navegando",                     ru: "Просматривает",                 tl: "Nagba-browse" },
  "feed.listHere":      { en: "List here $9.99",               id: "Daftar di sini $9.99",                  th: "ลงที่นี่ $9.99",                   vi: "Đăng ký tại đây $9.99",          ms: "Senarai di sini $9.99",             fr: "Lister ici 9,99$",               zh: "在此上架 $9.99",                 ja: "ここに掲載 $9.99",                ko: "여기 등록 $9.99",                 ar: "سجل هنا $9.99",                  hi: "यहाँ सूचीबद्ध करें $9.99",       es: "Listar aquí $9.99",             de: "Hier auflisten $9.99",          pt: "Listar aqui $9.99",             ru: "Разместить здесь $9.99",        tl: "Ilista dito $9.99" },
  "feed.noProfiles":    { en: "No more profiles",              id: "Tidak ada profil lagi",                 th: "ไม่มีโปรไฟล์เพิ่มเติม",           vi: "Không còn hồ sơ",               ms: "Tiada lagi profil",                 fr: "Plus de profils",                zh: "没有更多档案",                    ja: "プロフィールはありません",         ko: "더 이상 프로필 없음",              ar: "لا مزيد من الملفات",             hi: "और कोई प्रोफाइल नहीं",            es: "No hay más perfiles",           de: "Keine weiteren Profile",        pt: "Sem mais perfis",               ru: "Больше нет профилей",           tl: "Wala nang mga profile" },

  // ── Profile card ──────────────────────────────────────────────────────────────
  "card.tonight":       { en: "Tonight",                       id: "Malam ini",                             th: "คืนนี้",                           vi: "Tối nay",                        ms: "Malam ini",                         fr: "Ce soir",                        zh: "今晚",                           ja: "今夜",                            ko: "오늘 밤",                          ar: "الليلة",                         hi: "आज रात",                         es: "Esta noche",                    de: "Heute Nacht",                   pt: "Esta noite",                    ru: "Сегодня вечером",               tl: "Ngayong gabi" },
  "card.members":       { en: "MEMBERS",                       id: "ANGGOTA",                               th: "สมาชิก",                           vi: "THÀNH VIÊN",                     ms: "AHLI",                              fr: "MEMBRES",                        zh: "会员",                           ja: "メンバー",                        ko: "회원",                            ar: "الأعضاء",                        hi: "सदस्य",                           es: "MIEMBROS",                      de: "MITGLIEDER",                    pt: "MEMBROS",                       ru: "УЧАСТНИКИ",                     tl: "MGA MIYEMBRO" },
  "card.verified":      { en: "Verified",                      id: "Terverifikasi",                         th: "ยืนยันแล้ว",                       vi: "Đã xác minh",                    ms: "Disahkan",                          fr: "Vérifié",                        zh: "已验证",                         ja: "認証済み",                        ko: "인증됨",                          ar: "موثق",                           hi: "सत्यापित",                        es: "Verificado",                    de: "Verifiziert",                   pt: "Verificado",                    ru: "Подтверждён",                   tl: "Verified" },
  "card.online":        { en: "Online",                        id: "Online",                                th: "ออนไลน์",                          vi: "Trực tuyến",                     ms: "Dalam talian",                      fr: "En ligne",                       zh: "在线",                           ja: "オンライン",                      ko: "온라인",                          ar: "متصل",                           hi: "ऑनलाइन",                         es: "En línea",                      de: "Online",                        pt: "Online",                        ru: "Онлайн",                        tl: "Online" },
  "card.woman":         { en: "Woman",                         id: "Wanita",                                th: "ผู้หญิง",                          vi: "Phụ nữ",                         ms: "Wanita",                            fr: "Femme",                          zh: "女性",                           ja: "女性",                            ko: "여성",                            ar: "امرأة",                          hi: "महिला",                           es: "Mujer",                         de: "Frau",                          pt: "Mulher",                        ru: "Женщина",                       tl: "Babae" },
  "card.man":           { en: "Man",                           id: "Pria",                                  th: "ผู้ชาย",                           vi: "Đàn ông",                        ms: "Lelaki",                            fr: "Homme",                          zh: "男性",                           ja: "男性",                            ko: "남성",                            ar: "رجل",                            hi: "पुरुष",                           es: "Hombre",                        de: "Mann",                          pt: "Homem",                         ru: "Мужчина",                       tl: "Lalaki" },

  // ── Buttons ───────────────────────────────────────────────────────────────────
  "btn.like":           { en: "Like",                          id: "Suka",                                  th: "ถูกใจ",                            vi: "Thích",                          ms: "Suka",                              fr: "J'aime",                         zh: "喜欢",                           ja: "いいね",                          ko: "좋아요",                          ar: "إعجاب",                          hi: "पसंद",                            es: "Me gusta",                      de: "Gefällt mir",                   pt: "Curtir",                        ru: "Нравится",                      tl: "Gusto" },
  "btn.pass":           { en: "Pass",                          id: "Lewati",                                th: "ข้าม",                             vi: "Bỏ qua",                         ms: "Lepas",                             fr: "Passer",                         zh: "跳过",                           ja: "パス",                            ko: "패스",                            ar: "تخطي",                           hi: "पास",                             es: "Pasar",                         de: "Weiter",                        pt: "Passar",                        ru: "Пропустить",                    tl: "Lumipas" },
  "btn.connect":        { en: "Connect",                       id: "Hubungkan",                             th: "เชื่อมต่อ",                        vi: "Kết nối",                        ms: "Sambung",                           fr: "Connecter",                      zh: "连接",                           ja: "つながる",                        ko: "연결",                            ar: "تواصل",                          hi: "कनेक्ट करें",                     es: "Conectar",                      de: "Verbinden",                     pt: "Conectar",                      ru: "Подключиться",                  tl: "Kumonekta" },
  "btn.unlock":         { en: "Unlock to Connect",             id: "Buka untuk Menghubungi",                th: "ปลดล็อกเพื่อเชื่อมต่อ",           vi: "Mở khóa để kết nối",            ms: "Buka kunci untuk menyambung",       fr: "Débloquer pour connecter",       zh: "解锁以连接",                     ja: "ロック解除して接続",               ko: "잠금 해제하여 연결",               ar: "افتح القفل للتواصل",             hi: "कनेक्ट करने के लिए अनलॉक करें",  es: "Desbloquear para conectar",     de: "Entsperren zum Verbinden",      pt: "Desbloquear para conectar",     ru: "Разблокировать для подключения", tl: "I-unlock para Kumonekta" },
  "btn.joinGhost":      { en: "Join Ghost Vaults",              id: "Gabung Ghost Vaults",                    th: "เข้าร่วม Ghost Vaults",             vi: "Tham gia Ghost Vaults",           ms: "Sertai Ghost Vaults",               fr: "Rejoindre Ghost Vaults",         zh: "加入 Ghost Vaults",              ja: "Ghost Vaults に参加",             ko: "Ghost Vaults 참여",               ar: "انضم إلى Ghost Vaults",          hi: "Ghost Vaults से जुड़ें",          es: "Unirse a Ghost Vaults",         de: "Ghost Vaults beitreten",        pt: "Entrar no Ghost Vaults",        ru: "Присоединиться к Ghost Vaults", tl: "Sumali sa Ghost Vaults" },
  "btn.enterGhostMode": { en: "Enter Ghost Mode",              id: "Masuk Ghost Mode",                      th: "เข้าสู่ Ghost Mode",               vi: "Vào Ghost Mode",                 ms: "Masuk Ghost Mode",                  fr: "Entrer en Ghost Mode",           zh: "进入幽灵模式",                    ja: "ゴーストモードへ",                 ko: "고스트 모드 진입",                ar: "ادخل وضع الشبح",                 hi: "घोस्ट मोड में प्रवेश करें",      es: "Entrar en Modo Fantasma",       de: "Ghost-Modus betreten",          pt: "Entrar no Modo Fantasma",       ru: "Войти в режим призрака",        tl: "Pumasok sa Ghost Mode" },
  "btn.save":           { en: "Save",                          id: "Simpan",                                th: "บันทึก",                           vi: "Lưu",                            ms: "Simpan",                            fr: "Enregistrer",                    zh: "保存",                           ja: "保存",                            ko: "저장",                            ar: "حفظ",                            hi: "सहेजें",                          es: "Guardar",                       de: "Speichern",                     pt: "Salvar",                        ru: "Сохранить",                     tl: "I-save" },
  "btn.back":           { en: "Back",                          id: "Kembali",                               th: "กลับ",                             vi: "Trở lại",                        ms: "Kembali",                           fr: "Retour",                         zh: "返回",                           ja: "戻る",                            ko: "뒤로",                            ar: "رجوع",                           hi: "वापस",                            es: "Volver",                        de: "Zurück",                        pt: "Voltar",                        ru: "Назад",                         tl: "Bumalik" },
  "btn.cancel":         { en: "Cancel",                        id: "Batal",                                 th: "ยกเลิก",                           vi: "Hủy",                            ms: "Batal",                             fr: "Annuler",                        zh: "取消",                           ja: "キャンセル",                      ko: "취소",                            ar: "إلغاء",                          hi: "रद्द करें",                       es: "Cancelar",                      de: "Abbrechen",                     pt: "Cancelar",                      ru: "Отмена",                        tl: "Kanselahin" },
  "btn.close":          { en: "Close",                         id: "Tutup",                                 th: "ปิด",                              vi: "Đóng",                           ms: "Tutup",                             fr: "Fermer",                         zh: "关闭",                           ja: "閉じる",                          ko: "닫기",                            ar: "إغلاق",                          hi: "बंद करें",                        es: "Cerrar",                        de: "Schließen",                     pt: "Fechar",                        ru: "Закрыть",                       tl: "Isara" },
  "btn.confirm":        { en: "Confirm",                       id: "Konfirmasi",                            th: "ยืนยัน",                           vi: "Xác nhận",                       ms: "Sahkan",                            fr: "Confirmer",                      zh: "确认",                           ja: "確認",                            ko: "확인",                            ar: "تأكيد",                          hi: "पुष्टि करें",                     es: "Confirmar",                     de: "Bestätigen",                    pt: "Confirmar",                     ru: "Подтвердить",                   tl: "Kumpirmahin" },
  "btn.justBrowsing":   { en: "Just browsing for now",         id: "Hanya melihat-lihat",                   th: "แค่ดูก่อน",                        vi: "Chỉ xem thôi",                   ms: "Sekadar melayari",                  fr: "Je regarde pour l'instant",      zh: "先随便看看",                     ja: "今は見ているだけ",                 ko: "지금은 그냥 둘러보기",             ar: "أتصفح فقط الآن",                hi: "अभी बस देख रहा हूँ",              es: "Solo mirando por ahora",        de: "Nur schauen für jetzt",         pt: "Só navegando por agora",        ru: "Просто смотрю пока",            tl: "Nagba-browse lang muna" },

  // ── Setup page ────────────────────────────────────────────────────────────────
  "setup.title":        { en: "Create your Ghost Profile",     id: "Buat Profil Ghost Anda",                th: "สร้างโปรไฟล์ Ghost ของคุณ",        vi: "Tạo hồ sơ Ghost của bạn",       ms: "Buat Profil Ghost anda",            fr: "Créer votre profil Ghost",       zh: "创建您的幽灵档案",               ja: "ゴーストプロフィールを作成",       ko: "고스트 프로필 만들기",             ar: "أنشئ ملفك الشخصي",              hi: "अपनी Ghost प्रोफ़ाइल बनाएं",    es: "Crea tu perfil Ghost",          de: "Dein Ghost-Profil erstellen",   pt: "Criar seu perfil Ghost",        ru: "Создать Ghost профиль",         tl: "Gumawa ng iyong Ghost Profile" },
  "setup.photo":        { en: "Your photo",                    id: "Foto Anda",                             th: "รูปของคุณ",                        vi: "Ảnh của bạn",                    ms: "Foto anda",                         fr: "Votre photo",                    zh: "您的照片",                       ja: "あなたの写真",                    ko: "내 사진",                         ar: "صورتك",                          hi: "आपकी फ़ोटो",                      es: "Tu foto",                       de: "Dein Foto",                     pt: "Sua foto",                      ru: "Ваше фото",                     tl: "Ang iyong larawan" },
  "setup.name":         { en: "Your name",                     id: "Nama Anda",                             th: "ชื่อของคุณ",                       vi: "Tên của bạn",                    ms: "Nama anda",                         fr: "Votre prénom",                   zh: "您的姓名",                       ja: "あなたの名前",                    ko: "내 이름",                         ar: "اسمك",                           hi: "आपका नाम",                        es: "Tu nombre",                     de: "Dein Name",                     pt: "Seu nome",                      ru: "Ваше имя",                      tl: "Ang iyong pangalan" },
  "setup.age":          { en: "Your age",                      id: "Usia Anda",                             th: "อายุของคุณ",                       vi: "Tuổi của bạn",                   ms: "Umur anda",                         fr: "Votre âge",                      zh: "您的年龄",                       ja: "あなたの年齢",                    ko: "내 나이",                         ar: "عمرك",                           hi: "आपकी उम्र",                       es: "Tu edad",                       de: "Dein Alter",                    pt: "Sua idade",                     ru: "Ваш возраст",                   tl: "Ang iyong edad" },
  "setup.city":         { en: "Your city",                     id: "Kota Anda",                             th: "เมืองของคุณ",                      vi: "Thành phố của bạn",              ms: "Bandar anda",                       fr: "Votre ville",                    zh: "您的城市",                       ja: "あなたの都市",                    ko: "내 도시",                         ar: "مدينتك",                         hi: "आपका शहर",                        es: "Tu ciudad",                     de: "Deine Stadt",                   pt: "Sua cidade",                    ru: "Ваш город",                     tl: "Ang iyong lungsod" },
  "setup.gender":       { en: "I am a",                        id: "Saya seorang",                          th: "ฉันเป็น",                          vi: "Tôi là",                         ms: "Saya seorang",                      fr: "Je suis",                        zh: "我是",                           ja: "私は",                            ko: "나는",                            ar: "أنا",                            hi: "मैं हूँ",                         es: "Soy",                           de: "Ich bin",                       pt: "Eu sou",                        ru: "Я",                             tl: "Ako ay" },
  "setup.woman":        { en: "Woman",                         id: "Wanita",                                th: "ผู้หญิง",                          vi: "Phụ nữ",                         ms: "Wanita",                            fr: "Femme",                          zh: "女性",                           ja: "女性",                            ko: "여성",                            ar: "امرأة",                          hi: "महिला",                           es: "Mujer",                         de: "Frau",                          pt: "Mulher",                        ru: "Женщина",                       tl: "Babae" },
  "setup.man":          { en: "Man",                           id: "Pria",                                  th: "ผู้ชาย",                           vi: "Đàn ông",                        ms: "Lelaki",                            fr: "Homme",                          zh: "男性",                           ja: "男性",                            ko: "남성",                            ar: "رجل",                            hi: "पुरुष",                           es: "Hombre",                        de: "Mann",                          pt: "Homem",                         ru: "Мужчина",                       tl: "Lalaki" },
  "setup.bio":          { en: "Short bio (optional)",          id: "Bio singkat (opsional)",                th: "ประวัติสั้น (ไม่บังคับ)",          vi: "Giới thiệu ngắn (tùy chọn)",    ms: "Bio ringkas (pilihan)",             fr: "Courte bio (facultatif)",        zh: "简短介绍（可选）",               ja: "短い自己紹介（任意）",             ko: "짧은 소개 (선택)",                ar: "نبذة قصيرة (اختياري)",           hi: "संक्षिप्त परिचय (वैकल्पिक)",    es: "Bio corta (opcional)",          de: "Kurze Bio (optional)",          pt: "Bio curta (opcional)",          ru: "Краткая биография (необязательно)", tl: "Maikling bio (opsyonal)" },
  "setup.interests":    { en: "Your interests (pick up to 3)", id: "Minat Anda (pilih max 3)",              th: "ความสนใจ (เลือกได้ 3)",            vi: "Sở thích (chọn tối đa 3)",      ms: "Minat anda (pilih hingga 3)",       fr: "Vos intérêts (choisissez 3 max)", zh: "您的兴趣（最多选3个）",          ja: "あなたの趣味（3つまで）",          ko: "관심사 (최대 3개)",               ar: "اهتماماتك (اختر حتى 3)",        hi: "आपकी रुचियाँ (3 तक चुनें)",    es: "Tus intereses (elige hasta 3)", de: "Deine Interessen (bis zu 3)",   pt: "Seus interesses (escolha até 3)", ru: "Ваши интересы (до 3)",          tl: "Ang iyong mga interes (pumili ng hanggang 3)" },
  "setup.phone":        { en: "Your phone number",             id: "Nomor telepon Anda",                    th: "หมายเลขโทรศัพท์ของคุณ",           vi: "Số điện thoại của bạn",          ms: "Nombor telefon anda",               fr: "Votre numéro de téléphone",      zh: "您的电话号码",                   ja: "あなたの電話番号",                ko: "내 전화번호",                     ar: "رقم هاتفك",                      hi: "आपका फ़ोन नंबर",                  es: "Tu número de teléfono",         de: "Deine Telefonnummer",           pt: "Seu número de telefone",        ru: "Ваш номер телефона",            tl: "Ang iyong numero ng telepono" },
  "setup.phoneDesc":    { en: "Shared privately on mutual match", id: "Dibagikan saat mutual match",       th: "แชร์เป็นส่วนตัวเมื่อแมตช์กัน",   vi: "Chia sẻ riêng tư khi match",    ms: "Dikongsi peribadi apabila match",   fr: "Partagé en privé après un match mutuel", zh: "相互匹配后私下共享",             ja: "マッチング後に非公開で共有",       ko: "상호 매칭 시 비공개로 공유",       ar: "يُشارك بشكل خاص عند التطابق",  hi: "आपसी मैच पर निजी तौर पर साझा", es: "Compartido privadamente en match mutuo", de: "Privat geteilt bei gegenseitigem Match", pt: "Compartilhado privadamente em match mútuo", ru: "Приватно при взаимном матче",  tl: "Ibinabahagi nang pribado sa mutual match" },
  "setup.altPlatform":  { en: "Also on (optional)",            id: "Juga ada di (opsional)",                th: "ยังอยู่บน (ไม่บังคับ)",            vi: "Cũng dùng (tùy chọn)",          ms: "Juga di (pilihan)",                 fr: "Aussi sur (facultatif)",         zh: "也在（可选）",                   ja: "他のプラットフォーム（任意）",     ko: "또 있는 곳 (선택)",               ar: "متواجد أيضاً على (اختياري)",    hi: "इस पर भी (वैकल्पिक)",            es: "También en (opcional)",         de: "Auch auf (optional)",           pt: "Também em (opcional)",          ru: "Также на (необязательно)",      tl: "Nandoon din (opsyonal)" },
  "setup.saving":       { en: "Saving...",                     id: "Menyimpan...",                          th: "กำลังบันทึก...",                   vi: "Đang lưu...",                    ms: "Menyimpan...",                      fr: "Enregistrement...",              zh: "保存中...",                      ja: "保存中...",                       ko: "저장 중...",                      ar: "جارٍ الحفظ...",                  hi: "सहेजा जा रहा है...",             es: "Guardando...",                  de: "Speichern...",                  pt: "Salvando...",                   ru: "Сохранение...",                 tl: "Sine-save..." },
  "setup.privacy":      { en: "Your contact is shared privately after a mutual match only", id: "Kontak dibagikan privat setelah mutual match", th: "ข้อมูลติดต่อแชร์เป็นส่วนตัวหลัง mutual match เท่านั้น", vi: "Thông tin liên hệ chỉ chia sẻ riêng tư sau khi match", ms: "Kenalan dikongsi peribadi selepas mutual match sahaja", fr: "Vos coordonnées sont partagées en privé après un match mutuel uniquement", zh: "您的联系方式仅在相互匹配后私下共享", ja: "連絡先はマッチング後のみ非公開で共有", ko: "연락처는 상호 매칭 후에만 비공개로 공유", ar: "يُشارك جهة اتصالك بشكل خاص بعد التطابق المتبادل فقط", hi: "आपका संपर्क केवल आपसी मैच के बाद निजी तौर पर साझा होता है", es: "Tu contacto se comparte privadamente solo tras un match mutuo", de: "Dein Kontakt wird nur nach einem gegenseitigen Match privat geteilt", pt: "Seu contato é compartilhado privadamente apenas após match mútuo", ru: "Ваш контакт передаётся приватно только после взаимного матча", tl: "Ang iyong contact ay ibinabahagi nang pribado pagkatapos ng mutual match lamang" },
  "setup.enterGhost":   { en: "Enter Ghost Mode",              id: "Masuk Ghost Mode",                      th: "เข้าสู่ Ghost Mode",               vi: "Vào Ghost Mode",                 ms: "Masuk Ghost Mode",                  fr: "Entrer en Ghost Mode",           zh: "进入幽灵模式",                   ja: "ゴーストモードへ",                ko: "고스트 모드 진입",                ar: "ادخل وضع الشبح",                 hi: "घोस्ट मोड में प्रवेश करें",      es: "Entrar en Modo Fantasma",       de: "Ghost-Modus betreten",          pt: "Entrar no Modo Fantasma",       ru: "Войти в режим призрака",        tl: "Pumasok sa Ghost Mode" },

  // ── Ghost Vault ────────────────────────────────────────────────────────────────
  "room.title":         { en: "Ghost Vault",                    id: "Ghost Vault",                            th: "Ghost Vault",                      vi: "Ghost Vault",                    ms: "Ghost Vault",                        fr: "Ghost Vault",                    zh: "幽灵保险库",                     ja: "ゴーストボールト",                ko: "고스트 볼트",                     ar: "خزنة الشبح",                     hi: "Ghost Vault",                    es: "Ghost Vault",                   de: "Ghost Vault",                   pt: "Ghost Vault",                   ru: "Ghost Vault",                   tl: "Ghost Vault" },
  "room.matches":       { en: "Your Matches",                   id: "Match Anda",                             th: "แมตช์ของคุณ",                      vi: "Các cặp đôi của bạn",            ms: "Padanan anda",                       fr: "Vos matchs",                     zh: "您的匹配",                       ja: "あなたのマッチ",                  ko: "내 매칭",                         ar: "تطابقاتك",                       hi: "आपके मैच",                        es: "Tus matches",                   de: "Deine Matches",                 pt: "Seus matches",                  ru: "Ваши матчи",                    tl: "Ang iyong mga Match" },
  "room.noMatches":     { en: "No matches yet",                 id: "Belum ada match",                        th: "ยังไม่มีแมตช์",                    vi: "Chưa có cặp đôi",               ms: "Belum ada padanan",                  fr: "Pas encore de match",            zh: "暂无匹配",                       ja: "まだマッチなし",                  ko: "아직 매칭 없음",                  ar: "لا تطابقات بعد",                hi: "अभी तक कोई मैच नहीं",            es: "Sin matches aún",               de: "Noch keine Matches",            pt: "Sem matches ainda",             ru: "Пока нет матчей",               tl: "Wala pang mga Match" },
  "room.expires":       { en: "Expires in",                     id: "Kadaluarsa dalam",                       th: "หมดอายุใน",                        vi: "Hết hạn trong",                  ms: "Tamat dalam",                        fr: "Expire dans",                    zh: "到期于",                         ja: "有効期限",                        ko: "만료",                            ar: "ينتهي في",                       hi: "समाप्त होगा",                    es: "Expira en",                     de: "Läuft ab in",                   pt: "Expira em",                     ru: "Истекает через",                tl: "Mag-eexpire sa" },

  // ── Match popup ───────────────────────────────────────────────────────────────
  "match.title":        { en: "It's a Match!",                  id: "Ini Cocok!",                             th: "แมตช์กันแล้ว!",                    vi: "Đây là một cặp!",               ms: "Ini padanan!",                       fr: "C'est un match!",                zh: "匹配成功！",                     ja: "マッチしました！",                ko: "매칭됐어요!",                     ar: "إنه تطابق!",                     hi: "यह एक मैच है!",                  es: "¡Es un match!",                 de: "Ein Match!",                    pt: "É um match!",                   ru: "Это матч!",                     tl: "Match na!" },
  "match.likedEachOther": { en: "You liked each other",        id: "Kalian saling menyukai",                th: "คุณถูกใจซึ่งกันและกัน",            vi: "Các bạn thích nhau",             ms: "Anda saling menyukai",               fr: "Vous vous êtes aimés mutuellement", zh: "你们互相喜欢",                   ja: "お互いにいいねしました",           ko: "서로 좋아했어요",                 ar: "أعجبتما ببعضكما",               hi: "आप दोनों ने एक दूसरे को पसंद किया", es: "Se gustaron mutuamente",       de: "Ihr mögt euch gegenseitig",     pt: "Vocês se curtiram",             ru: "Вы понравились друг другу",     tl: "Nagustuhan ninyo ang isa't isa" },
  "match.connectNow":   { en: "Connect Now",                    id: "Hubungi Sekarang",                       th: "เชื่อมต่อตอนนี้",                  vi: "Kết nối ngay",                   ms: "Sambung sekarang",                   fr: "Connecter maintenant",           zh: "立即连接",                       ja: "今すぐつながる",                  ko: "지금 연결",                       ar: "تواصل الآن",                     hi: "अभी कनेक्ट करें",               es: "Conectar ahora",                de: "Jetzt verbinden",               pt: "Conectar agora",                ru: "Подключиться сейчас",           tl: "Kumonekta Ngayon" },
  "match.later":        { en: "Maybe later",                    id: "Mungkin nanti",                          th: "ไว้คราวหลัง",                      vi: "Có thể sau",                     ms: "Mungkin nanti",                      fr: "Peut-être plus tard",            zh: "也许稍后",                       ja: "後で",                            ko: "나중에",                          ar: "ربما لاحقاً",                    hi: "शायद बाद में",                   es: "Quizás después",                de: "Vielleicht später",             pt: "Talvez depois",                 ru: "Может быть позже",              tl: "Marahil mamaya" },
  "match.connected":    { en: "You're Connected!",              id: "Anda Terhubung!",                        th: "คุณเชื่อมต่อแล้ว!",               vi: "Bạn đã kết nối!",               ms: "Anda Tersambung!",                   fr: "Vous êtes connectés!",           zh: "您已连接！",                     ja: "接続しました！",                  ko: "연결됐어요!",                     ar: "أنت متصل!",                      hi: "आप कनेक्ट हो गए!",              es: "¡Estás conectado!",             de: "Du bist verbunden!",            pt: "Você está conectado!",          ru: "Вы подключены!",                tl: "Nakakonekta ka na!" },

  // ── Paywall ───────────────────────────────────────────────────────────────────
  "pay.womenFree":      { en: "Women join free forever",        id: "Wanita gratis selamanya",               th: "ผู้หญิงเข้าร่วมฟรีตลอดไป",        vi: "Phụ nữ tham gia miễn phí",      ms: "Wanita sertai percuma selamanya",   fr: "Les femmes rejoignent gratuitement", zh: "女性永久免费加入",               ja: "女性は永久無料",                  ko: "여성은 영구 무료",                ar: "تنضم النساء مجاناً إلى الأبد",  hi: "महिलाएं हमेशा के लिए मुफ्त",    es: "Las mujeres se unen gratis para siempre", de: "Frauen nehmen für immer kostenlos teil", pt: "Mulheres entram grátis para sempre", ru: "Женщины вступают бесплатно навсегда", tl: "Libre ang kababaihan magpakailanman" },
  "pay.foundingGhost":  { en: "Founding Ghost",                 id: "Founding Ghost",                        th: "Founding Ghost",                   vi: "Founding Ghost",                 ms: "Founding Ghost",                    fr: "Founding Ghost",                 zh: "创始幽灵",                       ja: "ファウンディングゴースト",         ko: "파운딩 고스트",                   ar: "المؤسس الشبح",                   hi: "फाउंडिंग घोस्ट",                es: "Ghost Fundador",                de: "Founding Ghost",                pt: "Ghost Fundador",                ru: "Основатель Ghost",              tl: "Founding Ghost" },
  "pay.monthly":        { en: "Ghost Monthly",                  id: "Ghost Bulanan",                         th: "Ghost รายเดือน",                   vi: "Ghost hàng tháng",               ms: "Ghost Bulanan",                     fr: "Ghost Mensuel",                  zh: "幽灵月度",                       ja: "ゴースト月額",                    ko: "고스트 월간",                     ar: "شبح شهري",                       hi: "Ghost मासिक",                    es: "Ghost Mensual",                 de: "Ghost Monatlich",               pt: "Ghost Mensal",                  ru: "Ghost Ежемесячный",             tl: "Ghost Buwanан" },
  "pay.perMonth":       { en: "per month · cancel anytime",     id: "per bulan · batalkan kapan saja",       th: "ต่อเดือน · ยกเลิกได้ตลอด",        vi: "mỗi tháng · hủy bất cứ lúc nào", ms: "sebulan · batalkan bila-bila masa", fr: "par mois · annuler à tout moment", zh: "每月 · 随时取消",                ja: "月額 · いつでもキャンセル",        ko: "월 · 언제든지 취소",              ar: "شهرياً · إلغاء في أي وقت",      hi: "प्रति माह · कभी भी रद्द करें",  es: "por mes · cancela cuando quieras", de: "pro Monat · jederzeit kündbar", pt: "por mês · cancele quando quiser", ru: "в месяц · отменить в любое время", tl: "bawat buwan · kanselahin anumang oras" },
  "pay.choosePlan":     { en: "Choose your plan",               id: "Pilih paket Anda",                      th: "เลือกแผนของคุณ",                   vi: "Chọn gói của bạn",               ms: "Pilih pelan anda",                  fr: "Choisissez votre forfait",       zh: "选择您的套餐",                   ja: "プランを選ぶ",                    ko: "플랜 선택",                       ar: "اختر خطتك",                      hi: "अपना प्लान चुनें",               es: "Elige tu plan",                 de: "Wähle deinen Plan",             pt: "Escolha seu plano",             ru: "Выберите план",                 tl: "Pumili ng plano" },

  // ── Dashboard ─────────────────────────────────────────────────────────────────
  "dash.title":         { en: "My Ghost Profile",               id: "Profil Ghost Saya",                     th: "โปรไฟล์ Ghost ของฉัน",             vi: "Hồ sơ Ghost của tôi",           ms: "Profil Ghost saya",                 fr: "Mon profil Ghost",               zh: "我的幽灵档案",                   ja: "私のゴーストプロフィール",         ko: "내 고스트 프로필",                ar: "ملفي الشخصي",                    hi: "मेरी Ghost प्रोफ़ाइल",           es: "Mi perfil Ghost",               de: "Mein Ghost-Profil",             pt: "Meu perfil Ghost",              ru: "Мой Ghost профиль",             tl: "Ang aking Ghost Profile" },
  "dash.likesToday":    { en: "Likes Today",                    id: "Suka Hari Ini",                         th: "ถูกใจวันนี้",                      vi: "Thích hôm nay",                  ms: "Suka Hari Ini",                     fr: "J'aime aujourd'hui",             zh: "今日点赞",                       ja: "本日のいいね",                    ko: "오늘 좋아요",                     ar: "إعجابات اليوم",                  hi: "आज की पसंद",                    es: "Likes hoy",                     de: "Likes heute",                   pt: "Curtidas hoje",                 ru: "Лайки сегодня",                 tl: "Mga Like Ngayon" },
  "dash.streak":        { en: "Day Streak",                     id: "Hari Berturut",                         th: "วันต่อเนื่อง",                     vi: "Chuỗi ngày",                     ms: "Hari Berturut",                     fr: "Série de jours",                 zh: "连续天数",                       ja: "連続日数",                        ko: "연속 일수",                       ar: "أيام متتالية",                   hi: "लगातार दिन",                    es: "Racha de días",                 de: "Tages-Serie",                   pt: "Sequência de dias",             ru: "Серия дней",                    tl: "Araw-araw na Streak" },
  "dash.matches":       { en: "Matches",                        id: "Match",                                 th: "แมตช์",                            vi: "Cặp đôi",                        ms: "Padanan",                           fr: "Matchs",                         zh: "匹配",                           ja: "マッチ",                          ko: "매칭",                            ar: "تطابقات",                        hi: "मैच",                             es: "Matches",                       de: "Matches",                       pt: "Matches",                       ru: "Матчи",                         tl: "Mga Match" },
  "dash.howIConnect":   { en: "How I Connect",                  id: "Cara Saya Terhubung",                   th: "วิธีที่ฉันเชื่อมต่อ",              vi: "Cách tôi kết nối",               ms: "Cara saya berhubung",               fr: "Comment je me connecte",         zh: "我的连接方式",                   ja: "接続方法",                        ko: "연결 방법",                       ar: "كيف أتواصل",                     hi: "मैं कैसे जुड़ता हूँ",             es: "Cómo me conecto",               de: "Wie ich mich verbinde",         pt: "Como me conecto",               ru: "Как я подключаюсь",             tl: "Paano Ako Kumokonekta" },
  "dash.activityToday": { en: "Activity Today",                 id: "Aktivitas Hari Ini",                    th: "กิจกรรมวันนี้",                    vi: "Hoạt động hôm nay",              ms: "Aktiviti Hari Ini",                 fr: "Activité aujourd'hui",           zh: "今日活动",                       ja: "本日の活動",                      ko: "오늘 활동",                       ar: "النشاط اليوم",                   hi: "आज की गतिविधि",                  es: "Actividad hoy",                 de: "Aktivität heute",               pt: "Atividade hoje",                ru: "Активность сегодня",            tl: "Aktibidad Ngayon" },

  // ── International Ghost ───────────────────────────────────────────────────────
  "intl.title":         { en: "International Ghost",            id: "Ghost Internasional",                   th: "Ghost นานาชาติ",                   vi: "Ghost Quốc tế",                  ms: "Ghost Antarabangsa",                fr: "Ghost International",            zh: "国际幽灵",                       ja: "インターナショナルゴースト",       ko: "인터내셔널 고스트",               ar: "الشبح الدولي",                   hi: "अंतर्राष्ट्रीय Ghost",           es: "Ghost Internacional",           de: "Internationaler Ghost",         pt: "Ghost Internacional",           ru: "Международный Ghost",           tl: "International Ghost" },
  "intl.desc":          { en: "List your profile in other countries", id: "Daftarkan profil di negara lain", th: "ลงโปรไฟล์ในประเทศอื่น",           vi: "Đăng hồ sơ ở các quốc gia khác", ms: "Senaraikan profil di negara lain", fr: "Listez votre profil dans d'autres pays", zh: "在其他国家展示您的档案",          ja: "他の国でプロフィールを掲載",       ko: "다른 나라에 프로필 등록",          ar: "أدرج ملفك في دول أخرى",         hi: "अन्य देशों में प्रोफ़ाइल सूचीबद्ध करें", es: "Lista tu perfil en otros países", de: "Dein Profil in anderen Ländern listen", pt: "Liste seu perfil em outros países", ru: "Разместите профиль в других странах", tl: "Ilista ang iyong profile sa ibang bansa" },
  "intl.freeForWomen":  { en: "Free for women",                 id: "Gratis untuk wanita",                   th: "ฟรีสำหรับผู้หญิง",                vi: "Miễn phí cho phụ nữ",           ms: "Percuma untuk wanita",              fr: "Gratuit pour les femmes",        zh: "女性免费",                       ja: "女性は無料",                      ko: "여성 무료",                       ar: "مجاني للنساء",                   hi: "महिलाओं के लिए मुफ्त",           es: "Gratis para mujeres",           de: "Kostenlos für Frauen",          pt: "Grátis para mulheres",          ru: "Бесплатно для женщин",          tl: "Libre para sa kababaihan" },
  "intl.perMonth":      { en: "$9.99 / month for men",          id: "$9.99 / bulan untuk pria",              th: "$9.99 / เดือน สำหรับผู้ชาย",      vi: "$9.99 / tháng cho đàn ông",     ms: "$9.99 / bulan untuk lelaki",        fr: "9,99$ / mois pour les hommes",   zh: "男性每月 $9.99",                 ja: "男性は月額 $9.99",                ko: "남성 월 $9.99",                   ar: "$9.99 / شهر للرجال",            hi: "पुरुषों के लिए $9.99/माह",       es: "$9.99 / mes para hombres",      de: "$9.99 / Monat für Männer",      pt: "$9.99 / mês para homens",       ru: "$9.99 / месяц для мужчин",      tl: "$9.99 / buwan para sa mga lalaki" },

  // ── Gateway / Welcome modal ───────────────────────────────────────────────────
  "gateway.welcome":    { en: "Welcome to Ghost Vaults",         id: "Selamat Datang di Ghost Vaults",         th: "ยินดีต้อนรับสู่ Ghost Vaults",     vi: "Chào mừng đến Ghost Vaults",    ms: "Selamat datang ke Ghost Vaults",    fr: "Bienvenue dans Ghost Vaults",    zh: "欢迎来到 Ghost Vaults",          ja: "Ghost Vaults へようこそ",         ko: "Ghost Vaults에 오신 것을 환영합니다", ar: "مرحباً في Ghost Vaults",        hi: "Ghost Vaults में आपका स्वागत है", es: "Bienvenido a Ghost Vaults",    de: "Willkommen bei Ghost Vaults",   pt: "Bem-vindo ao Ghost Vaults",     ru: "Добро пожаловать в Ghost Vaults", tl: "Maligayang pagdating sa Ghost Vaults" },
  "gateway.houseRules": { en: "The House Rules",                 id: "Aturan Rumah",                           th: "กฎของบ้าน",                        vi: "Quy tắc của nhà",               ms: "Peraturan Rumah",                    fr: "Les règles de la maison",        zh: "房间规则",                       ja: "ハウスルール",                    ko: "하우스 룰",                       ar: "قواعد المنزل",                   hi: "घर के नियम",                    es: "Las reglas de la casa",         de: "Die Hausregeln",                pt: "As regras da casa",             ru: "Правила дома",                  tl: "Ang Mga Patakaran ng Bahay" },
  "gateway.howItWorks": { en: "How Ghost Vaults Works",          id: "Cara Kerja Ghost Vaults",                th: "วิธีการทำงานของ Ghost Vaults",     vi: "Cách Ghost Vaults hoạt động",   ms: "Cara Ghost Vaults Berfungsi",       fr: "Comment Ghost Vaults fonctionne", zh: "Ghost Vaults 如何运作",          ja: "Ghost Vaults の仕組み",           ko: "Ghost Vaults 작동 방식",          ar: "كيف يعمل Ghost Vaults",         hi: "Ghost Vaults कैसे काम करता है", es: "Cómo funciona Ghost Vaults",   de: "Wie Ghost Vaults funktioniert", pt: "Como o Ghost Vaults funciona",  ru: "Как работает Ghost Vaults",     tl: "Paano gumagana ang Ghost Vaults" },
  "gateway.accept":     { en: "I accept Mr Butlas Rules",        id: "Saya menerima Aturan Mr Butlas",         th: "ฉันยอมรับกฎ Mr Butlas",           vi: "Tôi chấp nhận Quy tắc Mr Butlas", ms: "Saya terima Peraturan Mr Butlas",   fr: "J'accepte les règles Mr Butlas", zh: "我接受 Mr Butlas 规则",          ja: "Mr Butlas のルールに同意する",     ko: "Mr Butlas 규칙에 동의합니다",     ar: "أقبل قواعد Mr Butlas",          hi: "मैं Mr Butlas नियम स्वीकार करता हूँ", es: "Acepto las reglas de Mr Butlas", de: "Ich akzeptiere die Mr Butlas-Regeln", pt: "Aceito as regras do Mr Butlas", ru: "Принимаю правила Mr Butlas",    tl: "Tinatanggap ko ang Mga Patakaran ng Mr Butlas" },
  "gateway.entering":   { en: "Entering Ghost Mode...",          id: "Memasuki Ghost Mode...",                 th: "กำลังเข้าสู่ Ghost Mode...",       vi: "Đang vào Ghost Mode...",        ms: "Memasuki Ghost Mode...",            fr: "Entrée en Ghost Mode...",        zh: "正在进入幽灵模式...",            ja: "ゴーストモードへ入っています...",  ko: "고스트 모드 진입 중...",          ar: "جارٍ الدخول إلى وضع الشبح...",  hi: "घोस्ट मोड में प्रवेश हो रहा है...", es: "Entrando al Modo Fantasma...", de: "Ghost-Modus wird betreten...",  pt: "Entrando no Modo Fantasma...",  ru: "Вход в режим призрака...",      tl: "Pumapasok sa Ghost Mode..." },
  "gateway.previewMode":{ en: "You're in Preview Mode",          id: "Anda dalam Mode Pratinjau",              th: "คุณอยู่ในโหมดตัวอย่าง",           vi: "Bạn đang ở chế độ xem trước",  ms: "Anda dalam Mod Pratonton",          fr: "Vous êtes en mode aperçu",       zh: "您处于预览模式",                 ja: "プレビューモードです",             ko: "미리보기 모드입니다",             ar: "أنت في وضع المعاينة",           hi: "आप पूर्वावलोकन मोड में हैं",    es: "Estás en modo vista previa",    de: "Du bist im Vorschau-Modus",     pt: "Você está no modo de visualização", ru: "Вы в режиме предварительного просмотра", tl: "Nasa Preview Mode ka" },

  // ── General ───────────────────────────────────────────────────────────────────
  "general.km":         { en: "km",    id: "km",           th: "กม.",     vi: "km",          ms: "km",       fr: "km",    zh: "公里",  ja: "km",   ko: "km",   ar: "كم",   hi: "किमी",  es: "km",   de: "km",   pt: "km",   ru: "км",   tl: "km" },
  "general.free":       { en: "Free",  id: "Gratis",       th: "ฟรี",     vi: "Miễn phí",    ms: "Percuma",  fr: "Gratuit", zh: "免费", ja: "無料", ko: "무료", ar: "مجاني", hi: "मुफ्त", es: "Gratis", de: "Kostenlos", pt: "Grátis", ru: "Бесплатно", tl: "Libre" },
  "general.joinFree":   { en: "Join Free", id: "Daftar Gratis", th: "เข้าร่วมฟรี", vi: "Tham gia miễn phí", ms: "Sertai Percuma", fr: "Rejoindre gratuitement", zh: "免费加入", ja: "無料で参加", ko: "무료 가입", ar: "انضم مجاناً", hi: "मुफ्त में जुड़ें", es: "Unirse gratis", de: "Kostenlos beitreten", pt: "Entrar grátis", ru: "Присоединиться бесплатно", tl: "Sumali nang Libre" },
  "general.or":         { en: "or",    id: "atau",         th: "หรือ",    vi: "hoặc",        ms: "atau",     fr: "ou",    zh: "或",   ja: "または", ko: "또는", ar: "أو",  hi: "या",   es: "o",    de: "oder", pt: "ou",   ru: "или",  tl: "o" },
  "general.loading":    { en: "Loading...", id: "Memuat...", th: "กำลังโหลด...", vi: "Đang tải...", ms: "Memuatkan...", fr: "Chargement...", zh: "加载中...", ja: "読み込み中...", ko: "로딩 중...", ar: "جارٍ التحميل...", hi: "लोड हो रहा है...", es: "Cargando...", de: "Laden...", pt: "Carregando...", ru: "Загрузка...", tl: "Naglo-load..." },
} as const;
